#
# Copyright (c) 2025 David Marker <dave@freedave.net>
#
# SPDX-License-Identifier: BSD-2-Clause
#

#CONFDIR=        /usr/local/etc/rc.d
#CONFS=	netgraph

LOCALBASE?=/usr/local
BINDIR=	${LOCALBASE}/etc/rc.d
SCRIPTS=	netgraph


.include <bsd.prog.mk>
