#
# Copyright (c) 2025 David Marker <dave@freedave.net>
#
# SPDX-License-Identifier: BSD-2-Clause
#

LOCALBASE?=/usr/local
SCRIPTSDIR=${LOCALBASE}/etc/rc.d
DIRS+=  SCRIPTSDIR
SCRIPTS=	netgraph

beforeinstall : installdirs

.include <bsd.prog.mk>
