#
# Copyright (c) 2025 David Marker <dave@freedave.net>
#
# SPDX-License-Identifier: BSD-2-Clause
#

LOCALBASE?=/usr/local
BINDIR=	${LOCALBASE}/bin

SCRIPTS=	jeiface
#MAN=	jeiface.8

.include <bsd.prog.mk>
